### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by TheTreeofGrace**
Update for dependency vulnrabilities that have been resolved in newer versions.

### CODE REVIEW

**Comment by bnussman** [comment]
This is great. Fixes vulnerabilities in a dependency! Please merge 🥺🥺🥺

**Review by bnussman — APPROVED** [review]

**Comment by janaagaard75** [comment]
Has it been verified that it doesn't break anything upgrade `default-browser-id` from version 1 to version 3? When comparing the code changes, it looks like it's quite a rewrite of package.

https://github.com/sindresorhus/default-browser-id/compare/v1.0.3...v3.0.0

**Comment by chrisEff** [comment]
@janaagaard75 
I just ran the unit tests in this fork, they still pass.

**Comment by chrisEff** [comment]
...on the other hand, the only place where `default-browser-id` is being used is `lib/detect-mac.js`, which is unfortunately not covered by the tests... 😅

**Comment by janaagaard75** [comment]
> @janaagaard75 I just ran the unit tests in this fork, they still pass.

👍

**Comment by alopix** [comment]
As mentioned in #11, I do not think this PR can be merged, since `default-browser-id` in v3 has been turned into an ECMAScript Module, so using `require` would not work anymore.
#10 adds some tests for macOS and then #11 updates `default-browser-id` up until v2.

**Comment by jakub-g** [comment]
I merged #10 and #11 and released the new version. Closing this one.

**Pull request closed without merging**
