### PR TITLE
Added Windows 10 support

### PR DESCRIPTION
**Pull request by narekmalk**
Related to issue #5 
Changed the registry key to check in Windows 10 to "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\Shell\Associations\URLAssociations\http\UserChoice"
Added Edge check
Added tests for Windows 10

### CODE REVIEW

**Comment by jakub-g** [comment]
Hi @narekmal thanks for the PR! I will come back to it soon when I have some spare time
In the meantime it looks like jshint is complaining, can you check travis build output and do some small corrections?

Thanks!

**Comment by narekmalk** [comment]
Fixed

**Comment by narekmalk** [comment]
Hi @jakub-g, have you had chance to check?

**Comment by jakub-g** [comment]
0.4.0 pushed to npm, sorry the delay.
Thanks for the PR!

**Pull request merged**
